# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
