# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190128_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imageproject',
            name='project',
        ),
        migrations.DeleteModel(
            name='ImageProject',
        ),
    ]
