# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190131_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_lab_affiliate',
            field=models.BooleanField(default=False),
        ),
    ]
