# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_teammember_is_lab_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
