# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-17 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_partner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.CharField(blank=True, default='#', help_text='Link partner website', max_length=255, null=True, verbose_name='Url'),
        ),
    ]
