# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-21 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_partner_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name_plural': 'Team Members'},
        ),
    ]
