# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoslab', '0006_auto_20190127_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
