# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoslab', '0010_project_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
    ]
