# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoslab', '0011_remove_project_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageProject',
        ),
    ]
