# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-29 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoslab', '0018_auto_20190302_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Position Project', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Position Member', max_digits=5, null=True),
        ),
    ]
